name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: arduino/setup-arduino-cli@v1
      - id: cores
        name: Refresh Arduino cores
        run: |
          echo 'https://espressif.github.io/arduino-esp32/package_esp32_index.json' >~/arduino-cores.txt
          arduino-cli version
          arduino-cli update --additional-urls "$(<~/arduino-cores.txt)"
          echo ::set-output name=d::$(sha256sum ~/.arduino15/package_*index.json | sha256sum | cut -d' ' -f1)
      - name: Cache Arduino cores
        uses: actions/cache@v3
        with:
          path: ~/.arduino15/staging/packages
          key: cores-${{ steps.cores.outputs.d }}
      - name: Install Arduino cores
        run: |
          arduino-cli core install esp32:esp32 --additional-urls "$(<~/arduino-cores.txt)"
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends clang-format-11 doxygen
      - uses: actions/checkout@v3
      - name: Check code style
        run: |
          mk/format-code.sh
          git diff --exit-code
      - name: Prepare Arduino libraries
        run: |
          mkdir -p $HOME/Arduino/libraries
          cd $HOME/Arduino/libraries
          ln -s $GITHUB_WORKSPACE esp32cam
          mkdir -p AsyncTCP ESPAsyncWebServer ODROID-GO
          curl -fsLS https://github.com/me-no-dev/AsyncTCP/archive/${ASYNCTCP_VERSION}.tar.gz \
            | tar -C AsyncTCP -xz --strip-components=1
          curl -fsLS https://github.com/me-no-dev/ESPAsyncWebServer/archive/${ESPASYNCWEBSERVER_VERSION}.tar.gz \
            | tar -C ESPAsyncWebServer -xz --strip-components=1
          curl -fsLS https://github.com/hardkernel/ODROID-GO/archive/${ODROIDGO_VERSION}.tar.gz \
            | tar -C ODROID-GO -xz --strip-components=1 --wildcards '*/library.properties' '*/src/odroid_go.*' '*/src/Fonts' '*/src/utility'
        env:
          ASYNCTCP_VERSION: ca8ac5f919d02bea07b474531981ddbfd64de97c
          ESPASYNCWEBSERVER_VERSION: 1d46269cedf477661ca8a29518414f4b74e957d4
          ODROIDGO_VERSION: 4a496e337d16bca4ddedbeca3486d7b60662d017
      - name: Compile examples
        run: |
          arduino-cli compile -b esp32:esp32:esp32wrover ./examples/WifiCam
          arduino-cli compile -b esp32:esp32:esp32wrover ./examples/AsyncCam
          arduino-cli compile -b esp32:esp32:odroid_esp32 ./examples/GoDisplay
      - name: Build docs
        run: docs/build.sh
      - name: Deploy docs
        uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: 7de100ca-e942-419d-af2c-18e6c528b96e
          build-dir: ./docs/html/
        if: ${{ github.repository == 'yoursunny/esp32cam' && github.event_name == 'push' }}
